### ISSUE TITLE
ScoreBar has unused methods

### ISSUE THREAD

**Issue by CyrusVillaruz** [COMP2522/project-minihivemind#119]
https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/ScoreBar.java#L32

https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/ScoreBar.java#L37

https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/ScoreBar.java#L54

**Comment by elsaho** [comment]
Completed
