### ISSUE TITLE
Move filenames into Path or OS class

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-minihivemind#123]
https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/SoundEffects.java#L21

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html

**Comment by elsaho** [comment]
Do this for pictures too

**Comment by elsaho** [comment]
Nevermind :) Cannot do this with pictures
