### ISSUE TITLE
Condense for loops into one for conciseness

### ISSUE THREAD

**Issue by katelylynn** [COMP2522/project-minihivemind#151]
for ( Bubble bubble : bubbles ) {

  bubble.setup(parent);
  sprites.add(bubble);

}

https://github.com/COMP2522/project-minihivemind/blob/05abb14b71c023b894dfc940600e15bf5bc1ec80/src/main/java/org/ca/bcit/comp2522/Scene.java#L104-L110

**Comment by elsaho** [comment]
Completed
