### ISSUE TITLE
Refactor JSONWriteBubble.main() and extract useful functions

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-minihivemind#158]
https://github.com/COMP2522/project-minihivemind/blob/05abb14b71c023b894dfc940600e15bf5bc1ec80/src/main/java/org/ca/bcit/comp2522/JSONWriteBubble.java#L11-L49

Some of the lines here could be factored out into methods and be used in future level creation

**Comment by elsaho** [comment]
Deleted this class as we are no longer using
