### ISSUE TITLE
Update input handler for getLineInstance

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-minihivemind#212]

**Comment by TomaszStojek** [comment]
solved along with another issue, see : [Merge pull request](https://github.com/COMP2522/project-minihivemind/commit/ece310b6258be8f6f55deabe5fe2af32eadd6e00) https://github.com/COMP2522/project-minihivemind/pull/239 [from COMP2522/TS-186-refactor-line](https://github.com/COMP2522/project-minihivemind/commit/ece310b6258be8f6f55deabe5fe2af32eadd6e00) 

Ts 186 refactor line
