### ISSUE TITLE
Refactor GameWindow to handle different scenes with more flexibility

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-minihivemind#80]
Currently, different scenes are handled with a bunch of if statements: 

https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/GameWindow.java#L64

This may become cumbersome once you start adding more scenes such as settings, sub-settings, level select, main menu etc.

Try to find a way to refactor this to be more flexible with an increasing number of scenes

**Comment by elsaho** [comment]
Used enums to handle this
