### ISSUE TITLE
Add tests for classes

### ISSUE THREAD

**Issue by NicRodri** [COMP2522/project-minihivemind#86]
https://github.com/COMP2522/project-minihivemind/blob/9d968eff8b08da5a5308ad9060b599991f2412cf/src/main/java/org/ca/bcit/comp2522/GameWindow.java#L15

There are no unit tests for any of the classes

**Comment by TroyCalaquian** [comment]
This is not done yet. Tried Haurence's method of linking branches, but that only closes the issue when merged

**Comment by elsaho** [comment]
Nicolas your wish is my command
